
codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 50%
        threshold: 5%
    patch:
      default:
        target: 40%
        threshold: 5%
        # New SDK code has lower coverage initially
        informational: true 

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]

ignore:
  - "tests/**/*"
  - "**/*.test.*"